StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{646EA8541251AC36}" {
   Id "AresCore-EditableEntity_ArsenalBox_Name"
   Target_en_us "Ares PMC Arsenal"
   Status TRANSLATION_DONE
   Modified 1684977521
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{646EA85BE1529441}" {
   Id "AresCore-EditableEntity_SpawnPoint_Name"
   Target_en_us "Ares PMC Spawn Point"
   Status TRANSLATION_DONE
   Modified 1684977670
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{646EA85511323865}" {
   Id "AresCore-Faction_ARES"
   Target_en_us "Ares PMC"
   Status TRANSLATION_DONE
   Modified 1684977104
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{646EA8553FCDE248}" {
   Id "AresCore-Faction_ARES_Upper"
   Target_en_us "ARES"
   Status TRANSLATION_DONE
   Modified 1684977101
   Author "Hayden"
   LastChanged "Hayden"
  }
 }
}