StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{646EA8541251AC36}" {
   Id "AresCore-EditableEntity_ArsenalBox_Name"
   Target_en_us "Ares PMC Arsenal"
   Status TRANSLATION_DONE
   Modified 1684977521
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{64FB2777C45A5A9D}" {
   Id "AresCore-EditableEntity_ArsenalBox_Weapons_Equipment_Name"
   Target_en_us "Ares PMC Arsenal - Equipment"
   Status TRANSLATION_DONE
   Modified 1694182640
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{64FB2776325A5B45}" {
   Id "AresCore-EditableEntity_ArsenalBox_Weapons_Name"
   Target_en_us "Ares PMC Arsenal - Weapons"
   Status TRANSLATION_DONE
   Modified 1694182642
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{646EA85BE1529441}" {
   Id "AresCore-EditableEntity_SpawnPoint_Name"
   Target_en_us "Ares PMC Spawn Point"
   Status TRANSLATION_DONE
   Modified 1684977670
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{64FB1A8532772BBC}" {
   Id "AresCore-Editor_Mission_GM_Eden_Name"
   Target_en_us "[Ares PMC] Game Master - Everon"
   Status TRANSLATION_DONE
   Modified 1694180487
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{646EA85511323865}" {
   Id "AresCore-Faction_ARES"
   Target_en_us "Ares PMC"
   Status TRANSLATION_DONE
   Modified 1684977104
   Author "Hayden"
   LastChanged "Hayden"
  }
  CustomStringTableItem "{646EA8553FCDE248}" {
   Id "AresCore-Faction_ARES_Upper"
   Target_en_us "ARES"
   Status TRANSLATION_DONE
   Modified 1684977101
   Author "Hayden"
   LastChanged "Hayden"
  }
 }
}